#!/bin/bash

systemctl daemon-reexec
systemctl daemon-reload

# kong
systemctl enable kong
systemctl start kong

# postgres
systemctl enable postgres
systemctl start postgres

# postgrest
systemctl enable postgrest
systemctl start postgrest

# studio
systemctl enable studio
systemctl start studio